USE [master]
GO

/****** Object:  Database [default]    Script Date: 02.10.2022 07:20:37 ******/
CREATE DATABASE [default]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'default', FILENAME = N'/var/opt/mssql/data/default.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'default_log', FILENAME = N'/var/opt/mssql/data/default_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [default].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [default] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [default] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [default] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [default] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [default] SET ARITHABORT OFF 
GO

ALTER DATABASE [default] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [default] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [default] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [default] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [default] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [default] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [default] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [default] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [default] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [default] SET  DISABLE_BROKER 
GO

ALTER DATABASE [default] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [default] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [default] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [default] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [default] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [default] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [default] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [default] SET RECOVERY FULL 
GO

ALTER DATABASE [default] SET  MULTI_USER 
GO

ALTER DATABASE [default] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [default] SET DB_CHAINING OFF 
GO

ALTER DATABASE [default] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [default] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [default] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [default] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [default] SET QUERY_STORE = OFF
GO

ALTER DATABASE [default] SET  READ_WRITE 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ShortUrls](
	[ShortPath] [nchar](255) NOT NULL,
	[Location] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

